pipeline{
	agent any
	environment{
something = '1.0.0'

		secret = credentials('server-password')

}
parameters{
   choice(name:'VERSION', choices:['1.1.0','1.2.0','1.3.0'], description:'')
   booleanParam(name: 'executeTests', defaultValue:true, description:'') 
}

	stages{
		stage("build"){
			steps {
		    	echo 'building app'
			echo " User env variable : ${something}"
			}
		}
		stage("test"){
		    steps{
		    when{
		        expression{
		            
		            params.executeTests
		        }

		    }

		        echo 'testing app'
			    echo "Branch name: ${GIT_BRANCH}"
			    input('CONTINUE?')
			    echo "${secret}"

		        }
		    }

		
		stage("deploy"){
		    steps{
		        echo 'deploying app'
			    withCredentials([
				    usernamePassword(credentials:'server-password',usernameVariable: USER,passwordVariable:PWD)])
			    {
				    echo "USER ${USER} and PASS ${PWD}"
			    }
		    }

		}


	
	}
	
	post{
		always{
		echo 'always runs'
		}
		failure{
		echo 'FAILED'
		}
		success{
			echo 'Success'
		}
	
	}
}



